
const carsData = [
    {
        id: 1,
        brand: "Toyota",
        model: "Vios",
        type: "Compact",
        year: 2023,
        price: 2500,
        available: true,
        transmission: "Automatic",
        fuelType: "Gasoline",
        mileage: 15000,
        seats: 5,
        features: ["Touchscreen Display", "Bluetooth", "Backup Camera", "Keyless Entry", "Air Conditioning"],
        image: "images/vios.jpg",
        description: "Reliable and fuel-efficient compact sedan perfect for city driving and daily commutes in the Philippines."
    },
    {
        id: 2,
        brand: "Toyota",
        model: "Innova",
        type: "SUV",
        year: 2024,
        price: 4500,
        available: true,
        transmission: "Automatic",
        fuelType: "Diesel",
        mileage: 8000,
        seats: 7,
        features: ["3rd Row Seating", "Rear Air Conditioning", "Touchscreen", "Backup Camera", "Apple CarPlay"],
        image: "images/innova.jpg",
        description: "Versatile and spacious SUV ideal for Filipino families and group travel with excellent road presence."
    },
    {
        id: 3,
        brand: "Toyota",
        model: "Fortuner",
        type: "SUV",
        year: 2023,
        price: 5500,
        available: false,
        transmission: "Automatic",
        fuelType: "Diesel",
        mileage: 12000,
        seats: 7,
        features: ["4WD", "Leather Seats", "Sunroof", "Premium Audio", "360 Camera"],
        image: "images/fortuner.png",
        description: "Premium SUV with powerful performance, perfect for both city driving and provincial adventures."
    },
    {
        id: 4,
        brand: "Honda",
        model: "City",
        type: "Compact",
        year: 2023,
        price: 2800,
        available: true,
        transmission: "Automatic",
        fuelType: "Gasoline",
        mileage: 13500,
        seats: 5,
        features: ["Honda Sensing", "LED Headlights", "Push Button Start", "Touchscreen", "Rear Camera"],
        image: "images/city.jpg",
        description: "Stylish and efficient compact car with advanced safety features for Philippine road conditions."
    },
    {
        id: 5,
        brand: "Mitsubishi",
        model: "Mirage G4",
        type: "Economy",
        year: 2023,
        price: 1800,
        available: true,
        transmission: "Automatic",
        fuelType: "Gasoline",
        mileage: 18500,
        seats: 5,
        features: ["Fuel Efficient", "Air Conditioning", "Audio System", "Power Steering", "Dual Airbags"],
        image: "images/mirage.jpg",
        description: "Ultra fuel-efficient economy car perfect for budget-conscious travelers in the Philippines."
    },
    {
        id: 6,
        brand: "Nissan",
        model: "Terra",
        type: "SUV",
        year: 2024,
        price: 5200,
        available: true,
        transmission: "Automatic",
        fuelType: "Diesel",
        mileage: 5000,
        seats: 7,
        features: ["Intelligent 4WD", "Around View Monitor", "Leather Seats", "Apple CarPlay", "Auto Climate Control"],
        image: "images/terra.webp",
        description: "Rugged and capable SUV designed to handle diverse Philippine terrain with comfort and style."
    },
    {
        id: 7,
        brand: "Ford",
        model: "Everest",
        type: "SUV",
        year: 2024,
        price: 5800,
        available: true,
        transmission: "Automatic",
        fuelType: "Diesel",
        mileage: 3200,
        seats: 7,
        features: ["Terrain Management", "SYNC 4", "Panoramic Sunroof", "Premium Sound", "Wireless Charging"],
        image: "images/everest.webp",
        description: "Sophisticated SUV with advanced technology and superior comfort for long Philippine drives."
    },
    {
        id: 8,
        brand: "Toyota",
        model: "Hiace",
        type: "Van",
        year: 2023,
        price: 4800,
        available: true,
        transmission: "Automatic",
        fuelType: "Diesel",
        mileage: 22000,
        seats: 12,
        features: ["Spacious Interior", "Rear Aircon", "Touchscreen", "Backup Camera", "Comfortable Seating"],
        image: "images/hiace.webp",
        description: "Iconic Philippine van perfect for large groups, family outings, and business transportation needs."
    },
    {
        id: 9,
        brand: "Hyundai",
        model: "Stargazer",
        type: "MPV",
        year: 2024,
        price: 3800,
        available: true,
        transmission: "Automatic",
        fuelType: "Gasoline",
        mileage: 7500,
        seats: 7,
        features: ["Sliding Doors", "Roof Rails", "Touchscreen", "Wireless Charging", "Multiple USB Ports"],
        image: "images/stargazer.avif",
        description: "Modern and stylish MPV with flexible seating perfect for growing Filipino families."
    },
    {
        id: 10,
        brand: "MG",
        model: "ZS",
        type: "Compact SUV",
        year: 2023,
        price: 3200,
        available: true,
        transmission: "Automatic",
        fuelType: "Gasoline",
        mileage: 11000,
        seats: 5,
        features: ["Panoramic Sunroof", "Touchscreen", "Rear Camera", "Apple CarPlay", "LED DRL"],
        image: "images/zs.webp",
        description: "Value-packed compact SUV offering premium features at an affordable price point."
    },
    {
        id: 11,
        brand: "Suzuki",
        model: "Ertiga",
        type: "MPV",
        year: 2023,
        price: 2600,
        available: true,
        transmission: "Automatic",
        fuelType: "Gasoline",
        mileage: 16800,
        seats: 7,
        features: ["Fuel Efficient", "Spacious Cabin", "Audio System", "Air Conditioning", "Rear Parking Sensor"],
        image: "images/ertiga.jpg",
        description: "Practical and economical MPV perfect for daily family use and weekend getaways."
    },
    {
        id: 12,
        brand: "Isuzu",
        model: "mu-X",
        type: "SUV",
        year: 2024,
        price: 5400,
        available: true,
        transmission: "Automatic",
        fuelType: "Diesel",
        mileage: 4200,
        seats: 7,
        features: ["4WD Capability", "Leather Seats", "Touchscreen", "Climate Control", "Premium Audio"],
        image: "images/mux.webp",
        description: "Durable and reliable SUV built to withstand challenging Philippine road conditions."
    }
];